site_name: Automate With ChatGPT
site_description: Converted Word documents, published via MkDocs + GitHub Pages
site_url: https://AutomateWithChatGPT.github.io/
repo_url: https://github.com/AutomateWithChatGPT/AutomateWithChatGPT.github.io
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - tables
  - footnotes
plugins:
  - search
docs_dir: docs
nav:
  - 'Welcome': index.md
  - 'echo-chamber-ai-exploitation': echo-chamber-ai-exploitation.md
  - 'echo-chamber-explanation-1': echo-chamber-explanation-1.md
  - 'echo-chamber-explanation': echo-chamber-explanation.md
  - 'echo-chamber-fraud-games': echo-chamber-fraud-games.md
  - 'echo-chamber-general-use': echo-chamber-general-use.md
  - 'echo-chamber-reference-1': echo-chamber-reference-1.md
  - 'echo-chamber-reference': echo-chamber-reference.md
  - 'echo-chamber-simulation-batch1-items1-25': echo-chamber-simulation-batch1-items1-25.md
  - 'echo-chamber-simulation-batch10-items226-250': echo-chamber-simulation-batch10-items226-250.md
  - 'echo-chamber-simulation-batch2-items26-50': echo-chamber-simulation-batch2-items26-50.md
  - 'echo-chamber-simulation-batch3-items51-75': echo-chamber-simulation-batch3-items51-75.md
  - 'echo-chamber-simulation-batch4-items76-100': echo-chamber-simulation-batch4-items76-100.md
  - 'echo-chamber-simulation-batch5-items101-125': echo-chamber-simulation-batch5-items101-125.md
  - 'echo-chamber-simulation-batch6-items126-150': echo-chamber-simulation-batch6-items126-150.md
  - 'echo-chamber-simulation-batch7-items151-175': echo-chamber-simulation-batch7-items151-175.md
  - 'echo-chamber-simulation-batch8-items176-200': echo-chamber-simulation-batch8-items176-200.md
  - 'echo-chamber-simulation-batch9-items201-225': echo-chamber-simulation-batch9-items201-225.md
  - 'echo-chamber-staged-vs-direct': echo-chamber-staged-vs-direct.md
  - 'echo-chamber-website-cloning-guide': echo-chamber-website-cloning-guide.md
  - 'jailbreak-techniques-examples': jailbreak-techniques-examples.md
  - 'malicious-custom-gpt-system-prompts': malicious-custom-gpt-system-prompts.md
  - 'other-jailbreak-techniques': other-jailbreak-techniques.md
  - 'red-flag-questions-250-detection-guide': red-flag-questions-250-detection-guide.md
  - 'supervisor-echo-chamber-simulation-guide': supervisor-echo-chamber-simulation-guide.md

