site_name: Automate With ChatGPT
site_description: Converted Word documents, published via MkDocs + GitHub Pages
site_url: https://AutomateWithChatGPT.github.io/
repo_url: https://github.com/AutomateWithChatGPT/AutomateWithChatGPT.github.io
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - tables
  - footnotes
plugins:
  - search
docs_dir: docs
